[package]
name = "testcontainers"
version = "0.5.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/testcontainers/testcontainers-rs"
categories = ["development-tools::testing"]
keywords = ["docker", "testcontainers"]
description = "Meta crate for testcontainers, a library for integration-testing against docker containers from within Rust."

[dependencies]
tc_core = { path = "../core", version = "0.2" }

# Clients
tc_cli_client = { path = "../cli_client", version = "0.1" }

# Images
tc_coblox_bitcoincore = { path = "../images/coblox_bitcoincore", version = "0.4" }
tc_trufflesuite_ganachecli = { path = "../images/trufflesuite_ganachecli", version = "0.3" }
tc_parity_parity = { path = "../images/parity_parity", version = "0.3" }
tc_dynamodb_local = { path = "../images/dynamodb_local", version = "0.1" }
tc_redis = { path = "../images/redis", version = "0.1" }
tc_elasticmq = { path = "../images/elasticmq", version = "0.1" }
tc_generic = { path = "../images/generic", version = "0.1" }
tc_postgres = { path = "../images/postgres", version = "0.1" }

[dev-dependencies]
bitcoin_rpc_client = "0.5"
spectral = "0.6"
web3 = "0.5"
pretty_env_logger = "0.3"
postgres = "0.15"

# Dynamodb client needed for dynamodb local
rusoto_core = "0.36"
rusoto_dynamodb = "0.36"
rusoto_credential = "0.15"

# Redis client
redis = "0.10"

# ElasticMQ (also requires rusoto_core, rusoto_credential)
rusoto_sqs = "0.36"
