[package]
name = "testcontainers"
version = "0.15.0"
authors.workspace = true
categories = ["development-tools::testing"]
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "A library for integration-testing against docker containers from within Rust."

[dependencies]
async-trait = { version = "0.1", optional = true }
bollard = { version = "0.16.1", optional = true }
bollard-stubs = "=1.44.0-rc.2"
conquer-once = { version = "0.4", optional = true }
futures = "0.3"
hex = "0.4"
hmac = "0.12"
log = "0.4"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
signal-hook = { version = "0.3", optional = true }
tokio = { version = "1", features = ["macros"], optional = true }

[features]
default = []
experimental = ["async-trait", "bollard", "tokio"]
watchdog = ["signal-hook", "conquer-once"]

[dev-dependencies]
pretty_env_logger = "0.5"
reqwest = { version = "0.12.3", features = ["blocking"] }
testimages.workspace = true
tokio = { version = "1", features = ["macros"] }
