[package]
name = "testcontainers"
version = "0.14.0"
authors = [ "CoBloX developers <team@coblox.tech>" ]
categories = [ "development-tools::testing" ]
edition = "2021"
keywords = [ "docker", "testcontainers" ]
license = "MIT OR Apache-2.0"
repository = "https://github.com/testcontainers/testcontainers-rs"
rust-version = "1.60.0"
description = "A library for integration-testing against docker containers from within Rust."

[dependencies]
async-trait = { version = "0.1", optional = true }
bollard = { version = "0.13.0", optional = true }
bollard-stubs = "=1.42.0-rc.3"
conquer-once = { version = "0.3", optional = true }
futures = "0.3"
log = "0.4"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
signal-hook = { version = "0.3", optional = true }
tokio = { version = "1", features = [ "macros" ], optional = true }

[features]
default = [ ]
watchdog = [ "signal-hook", "conquer-once" ]
experimental = [ "async-trait", "bollard", "tokio" ]

[dev-dependencies]
pretty_env_logger = "0.4"
postgres = "0.19"
reqwest = { version = "0.11", features = ["blocking"] }
spectral = "0.6"
tokio = { version = "1", features = [ "macros" ] }
