[package]
name = "testcontainers"
version = "0.15.0"
authors.workspace = true
categories = ["development-tools::testing"]
edition.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "A library for integration-testing against docker containers from within Rust."

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-trait = { version = "0.1" }
bollard = { version = "0.16.1", features = ["ssl"] }
bollard-stubs = "=1.44.0-rc.2"
conquer-once = { version = "0.4", optional = true }
dirs = "5.0.1"
futures = "0.3"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde-java-properties = "0.1.1"
serde_json = "1"
serde_with = "3.7.0"
signal-hook = { version = "0.3", optional = true }
tokio = { version = "1", features = ["macros", "fs", "rt-multi-thread"] }
tokio-util = "0.7.10"
url = { version = "2", features = ["serde"] }

[features]
default = []
blocking = []
watchdog = ["signal-hook", "conquer-once"]

[dev-dependencies]
pretty_env_logger = "0.5"
reqwest = { version = "0.12.3", features = ["blocking"] }
testimages.workspace = true
tokio = { version = "1", features = ["macros"] }
